[env:d1_mini_pro]
platform = espressif8266@^4.2.1
board = d1_mini_pro
framework = arduino
monitor_speed = 115200

lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    adafruit/Adafruit Si7021 Library@^1.5.3
    https://github.com/sparkfun/BMP180_Breakout_Arduino_Library.git
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
    https://github.com/aharshac/EasyNTPClient.git#f2431d8cbfc545b5f3d3acb17478dd1d833aa655
